// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cutwflpcyiuguoggwxwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1dHdmbHBjeWl1Z3VvZ2d3eHdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4Mjk4OTcsImV4cCI6MjA3NTQwNTg5N30.xoF8RlAYW9doOCRaHG-oBF4AFcFnbUPsaS-zipj7NaE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});